# Generated by Django 4.1.7 on 2023-03-27 12:37

import common.utils.upload_files
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "icon",
                    models.ImageField(
                        null=True,
                        upload_to=common.utils.upload_files.upload_icon,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("png",)
                            )
                        ],
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogs.catalog",
                    ),
                ),
            ],
            options={
                "db_table": "catalogs",
            },
        ),
        migrations.AddConstraint(
            model_name="catalog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent", None)),
                fields=("name",),
                name="unique_catalog_name",
            ),
        ),
    ]
