# Generated by Django 4.1.7 on 2023-04-07 10:22

import common.utils.upload_files
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0003_alter_catalog_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="icon",
            field=models.ImageField(
                null=True,
                upload_to=common.utils.upload_files.upload_icon,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=(
                            "jpeg",
                            "jpg",
                            "png",
                            "heic",
                            "heif",
                        ),
                        code="WRONG_IMAGE",
                        message="Wrong format uploaded image",
                    )
                ],
            ),
        ),
    ]
