# Generated by Django 4.1.7 on 2023-04-10 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0004_alter_catalog_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("searchable", models.BooleanField(default=False)),
                ("filtirable", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "templates",
            },
        ),
    ]
