# Generated by Django 4.1.7 on 2023-04-21 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0011_alter_catalog_name_alter_catalog_name_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="guid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="guid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
