# Generated by Django 4.1.7 on 2023-05-04 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0013_catalogfilterablefield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Template",
        ),
    ]
