# Generated by Django 4.1.7 on 2023-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogs", "0014_delete_template"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="catalogfilterablefield",
            constraint=models.UniqueConstraint(
                fields=("catalog", "option"), name="catalog_option_unique"
            ),
        ),
    ]
