# Generated by Django 4.1.7 on 2023-03-14 08:51

import django.db.models.deletion
from django.contrib.postgres.operations import (
    CreateExtension,
    TrigramExtension,
)
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CreateExtension('postgis'),
        CreateExtension('fuzzystrmatch'),
        CreateExtension('postgis_tiger_geocoder'),
        CreateExtension('postgis_topology'),
        CreateExtension('uuid-ossp'),
        TrigramExtension(),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_uz", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "regions",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_uz", models.CharField(max_length=100, null=True)),
                ("name_ru", models.CharField(max_length=100, null=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.region",
                    ),
                ),
            ],
            options={
                "db_table": "districts",
            },
        ),
        migrations.CreateModel(
            name="SelfPickUpAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        default="innmall/innmall.png", upload_to=""
                    ),
                ),
                ("address", models.TextField()),
                (
                    "phone",
                    models.CharField(
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="WRONG_PHONE_NUMBER",
                                message="Phone number must begin with 998 and contain only 12 numbers",
                                regex="^998\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=9, max_digits=12),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=9, max_digits=12),
                ),
            ],
            options={
                "abstract": False,
            },
        )
    ]
