# Generated by Django 4.1.7 on 2023-04-24 18:16

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="district_name_upper_index",
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="region_name_upper_index",
            ),
        ),
    ]
