# Generated by Django 4.1.7 on 2023-04-25 04:42

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_remove_district_district_name_upper_index_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="district",
            name="district_name_upper_index",
        ),
        migrations.RemoveIndex(
            model_name="region",
            name="region_name_upper_index",
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_uz"),
                    descending=True,
                ),
                name="district_name_uz_upper_index",
            ),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_ru"),
                    descending=True,
                ),
                name="district_name_ru_upper_index",
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_uz"),
                    descending=True,
                ),
                name="region_name_uz_upper_index",
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.text.Upper("name_ru"),
                    descending=True,
                ),
                name="region_name_ru_upper_index",
            ),
        ),
    ]
