# Generated by Django 4.1.7 on 2023-05-04 10:27

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_alter_optionvalue_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="option",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="option_name_upper_index",
            ),
        ),
    ]
